// ============================================================
// NAGAR CONNECT - SYSTEM CONSTANTS & ENUMS
// ============================================================

module.exports = {
  ROLES: {
    CITIZEN: 'CITIZEN',
    OFFICER: 'OFFICER',
    FIELD_STAFF: 'FIELD_STAFF',
    MUNICIPAL_ADMIN: 'MUNICIPAL_ADMIN',
    COMMISSIONER: 'COMMISSIONER',
    KNOWLEDGE_ADMIN: 'KNOWLEDGE_ADMIN',
    SUPER_ADMIN: 'SUPER_ADMIN'
  },

  COMPLAINT_STATUS: {
    SUBMITTED: 'SUBMITTED',
    UNDER_REVIEW: 'UNDER_REVIEW',
    ASSIGNED: 'ASSIGNED',
    FIELD_VERIFICATION: 'FIELD_VERIFICATION',
    IN_PROGRESS: 'IN_PROGRESS',
    RESOLUTION_SUBMITTED: 'RESOLUTION_SUBMITTED',
    CITIZEN_VERIFICATION: 'CITIZEN_VERIFICATION',
    RESOLVED: 'RESOLVED',
    CLOSED: 'CLOSED',
    REJECTED: 'REJECTED'
  },

  PRIORITY: {
    LOW: 'LOW',
    MEDIUM: 'MEDIUM',
    HIGH: 'HIGH',
    CRITICAL: 'CRITICAL'
  },

  SLA_STATUS: {
    ON_TRACK: 'ON_TRACK',
    APPROACHING_DEADLINE: 'APPROACHING_DEADLINE',
    OVERDUE: 'OVERDUE',
    BREACHED: 'BREACHED'
  },

  ESCALATION_LEVEL: {
    NONE: 'NONE',
    L1_OFFICER: 'L1_OFFICER',
    L2_COMMISSIONER: 'L2_COMMISSIONER',
    L3_ADMIN: 'L3_ADMIN'
  },

  COMMENT_TYPE: {
    INTERNAL_NOTE: 'INTERNAL_NOTE',
    CITIZEN_COMMUNICATION: 'CITIZEN_COMMUNICATION',
    CITIZEN_QUERY: 'CITIZEN_QUERY',
    FIELD_NOTE: 'FIELD_NOTE'
  },

  ASSIGNMENT_STATUS: {
    PENDING: 'PENDING',
    ACCEPTED: 'ACCEPTED',
    IN_PROGRESS: 'IN_PROGRESS',
    COMPLETED: 'COMPLETED',
    REASSIGNED: 'REASSIGNED',
    CANCELLED: 'CANCELLED'
  },

  JWT_SECRET: process.env.JWT_SECRET || 'nagar-connect-municipal-secure-jwt-secret-2026',
  JWT_EXPIRES_IN: '24h',
  PORT: process.env.PORT || 3000
};
